// <auto-generated />
using System;
using System.Collections.Generic;
using AdVision.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdVision.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418143521_DiscountsRemoveConstraints")]
    partial class DiscountsRemoveConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AdVision.Domain.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("number");

                    b.Property<DateOnly?>("SignedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("signed_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("AdVision.Domain.CustomerDiscounts.CustomerDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("DiscountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("discount_id");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("CustomerId", "DiscountId")
                        .IsUnique();

                    b.ToTable("customer_discounts", (string)null);
                });

            modelBuilder.Entity("AdVision.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("middle_name");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("AdVision.Domain.Discounts.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("MinTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("min_total");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("Percent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("percent");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("discounts", (string)null);
                });

            modelBuilder.Entity("AdVision.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("middle_name");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("position_id");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("AdVision.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contract_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("Status");

                    b.HasIndex("ContractId", "Status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("AdVision.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tariff_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.HasIndex("TariffId");

                    b.HasIndex("OrderId", "Status");

                    b.HasIndex("OrderId", "TariffId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("AdVision.Domain.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("AdVision.Domain.Tariffs.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("Price");

                    b.HasIndex("VenueId");

                    b.HasIndex("VenueId", "Price");

                    b.ToTable("tariffs", (string)null);
                });

            modelBuilder.Entity("AdVision.Domain.VenueTypes.VenueType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("venue_types", (string)null);
                });

            modelBuilder.Entity("AdVision.Domain.Venues.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<Guid>("VenueTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("venue_type_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "AdVision.Domain.Venues.Venue.Name#VenueName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Rating", "AdVision.Domain.Venues.Venue.Rating#VenueRating", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Value")
                                .HasColumnType("REAL")
                                .HasColumnName("rating");
                        });

                    b.HasKey("Id");

                    b.HasIndex("VenueTypeId");

                    b.ToTable("venues", null, t =>
                        {
                            t.HasCheckConstraint("CK_Venue_City", "length(\"city\") >= 10 AND length(\"city\") <= 300");

                            t.HasCheckConstraint("CK_Venue_District", "length(\"district\") >= 10 AND length(\"district\") <= 300");

                            t.HasCheckConstraint("CK_Venue_Height", "\"height\" >= 100 AND \"height\" <= 10000");

                            t.HasCheckConstraint("CK_Venue_House_NotEmpty", "length(\"house\") > 0");

                            t.HasCheckConstraint("CK_Venue_Latitude", "\"latitude\" >= -90 AND \"latitude\" <= 90");

                            t.HasCheckConstraint("CK_Venue_Longitude", "\"longitude\" >= -180 AND \"longitude\" <= 180");

                            t.HasCheckConstraint("CK_Venue_Rating", "\"rating\" >= 1 AND \"rating\" <= 10");

                            t.HasCheckConstraint("CK_Venue_Region", "length(\"region\") >= 10 AND length(\"region\") <= 300");

                            t.HasCheckConstraint("CK_Venue_Street", "length(\"street\") >= 10 AND length(\"street\") <= 300");

                            t.HasCheckConstraint("CK_Venue_Width", "\"width\" >= 100 AND \"width\" <= 10000");
                        });
                });

            modelBuilder.Entity("AdVision.Domain.Contracts.Contract", b =>
                {
                    b.HasOne("AdVision.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdVision.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AdVision.Domain.DateInterval", "DateInterval", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("start_date");

                            b1.HasKey("ContractId");

                            b1.ToTable("contracts");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("DateInterval")
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AdVision.Domain.CustomerDiscounts.CustomerDiscount", b =>
                {
                    b.HasOne("AdVision.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdVision.Domain.Discounts.Discount", "Discount")
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("AdVision.Domain.Customers.Customer", b =>
                {
                    b.OwnsOne("AdVision.Domain.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phone_number");

                            b1.HasKey("CustomerId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("AdVision.Domain.Employees.Employee", b =>
                {
                    b.HasOne("AdVision.Domain.Positions.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AdVision.Domain.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phone_number");

                            b1.HasKey("EmployeeId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("AdVision.Domain.Employees.Passport", "Passport", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("TEXT")
                                .HasColumnName("passport_number");

                            b1.Property<string>("Series")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("TEXT")
                                .HasColumnName("passport_series");

                            b1.HasKey("EmployeeId");

                            b1.HasIndex("Series", "Number")
                                .IsUnique();

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Passport")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("AdVision.Domain.Orders.Order", b =>
                {
                    b.HasOne("AdVision.Domain.Contracts.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AdVision.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("AdVision.Domain.Orders.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdVision.Domain.Tariffs.Tariff", null)
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AdVision.Domain.DateInterval", "Period", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("start_date");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("order_items");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("AdVision.Domain.Tariffs.Tariff", b =>
                {
                    b.HasOne("AdVision.Domain.Venues.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AdVision.Domain.DateInterval", "Interval", b1 =>
                        {
                            b1.Property<Guid>("TariffId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("start_date");

                            b1.HasKey("TariffId");

                            b1.HasIndex("EndDate");

                            b1.HasIndex("StartDate");

                            b1.HasIndex("StartDate", "EndDate");

                            b1.ToTable("tariffs");

                            b1.WithOwner()
                                .HasForeignKey("TariffId");
                        });

                    b.Navigation("Interval")
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("AdVision.Domain.Venues.Venue", b =>
                {
                    b.HasOne("AdVision.Domain.VenueTypes.VenueType", "Type")
                        .WithMany()
                        .HasForeignKey("VenueTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AdVision.Domain.Venues.VenueAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("VenueId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("city");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("district");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("house");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("longitude");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("street");

                            b1.HasKey("VenueId");

                            b1.HasIndex("Latitude", "Longitude")
                                .IsUnique();

                            b1.ToTable("venues");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });

                    b.OwnsOne("AdVision.Domain.Venues.VenueSize", "Size", b1 =>
                        {
                            b1.Property<Guid>("VenueId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Height")
                                .HasColumnType("REAL")
                                .HasColumnName("height");

                            b1.Property<double>("Width")
                                .HasColumnType("REAL")
                                .HasColumnName("width");

                            b1.HasKey("VenueId");

                            b1.ToTable("venues");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Size")
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("AdVision.Domain.Orders.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
