// <auto-generated />
using System;
using System.Collections.Generic;
using AdVision.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdVision.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414095603_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AdVision.Domain.VenueTypes.VenueType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("venue_types", (string)null);
                });

            modelBuilder.Entity("AdVision.Domain.Venues.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.Property<Guid>("VenueTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("venue_type_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "AdVision.Domain.Venues.Venue.Name#VenueName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id");

                    b.HasIndex("VenueTypeId");

                    b.ToTable("venues", null, t =>
                        {
                            t.HasCheckConstraint("CK_Venue_City", "length(\"city\") >= 10 AND length(\"city\") <= 300");

                            t.HasCheckConstraint("CK_Venue_District", "length(\"district\") >= 10 AND length(\"district\") <= 300");

                            t.HasCheckConstraint("CK_Venue_Height", "\"height\" >= 100 AND \"height\" <= 10000");

                            t.HasCheckConstraint("CK_Venue_House_NotEmpty", "length(\"house\") > 0");

                            t.HasCheckConstraint("CK_Venue_Latitude", "\"latitude\" >= -90 AND \"latitude\" <= 90");

                            t.HasCheckConstraint("CK_Venue_Longitude", "\"longitude\" >= -180 AND \"longitude\" <= 180");

                            t.HasCheckConstraint("CK_Venue_Rating", "\"rating\" >= 1 AND \"rating\" <= 10");

                            t.HasCheckConstraint("CK_Venue_Region", "length(\"region\") >= 10 AND length(\"region\") <= 300");

                            t.HasCheckConstraint("CK_Venue_Street", "length(\"street\") >= 10 AND length(\"street\") <= 300");

                            t.HasCheckConstraint("CK_Venue_Width", "\"width\" >= 100 AND \"width\" <= 10000");
                        });
                });

            modelBuilder.Entity("AdVision.Domain.Venues.Venue", b =>
                {
                    b.HasOne("AdVision.Domain.VenueTypes.VenueType", "Type")
                        .WithMany()
                        .HasForeignKey("VenueTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AdVision.Domain.Venues.VenueAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("VenueId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("city");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("district");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("house");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("longitude");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("street");

                            b1.HasKey("VenueId");

                            b1.HasIndex("Latitude", "Longitude")
                                .IsUnique();

                            b1.ToTable("venues");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });

                    b.OwnsOne("AdVision.Domain.Venues.VenueSize", "Size", b1 =>
                        {
                            b1.Property<Guid>("VenueId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Height")
                                .HasColumnType("REAL")
                                .HasColumnName("height");

                            b1.Property<double>("Width")
                                .HasColumnType("REAL")
                                .HasColumnName("width");

                            b1.HasKey("VenueId");

                            b1.ToTable("venues");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Size")
                        .IsRequired();

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
